### ISSUE TITLE
Grant type not allowed for the client

### ISSUE THREAD

**Issue by haydenholligan** [auth0/Auth0.swift#127]
So we found this error while switching over to new dev accounts today. 

![image](https://user-images.githubusercontent.com/9373998/27519183-79602692-59a3-11e7-9a64-819ba8e245cc.png)

I read about it [here](https://community.auth0.com/questions/3944/error-grant-type-password-not-allowed-for-the-clie) and [here](https://github.com/auth0/react-native-lock/issues/165). I've updated Auth0 to v1.6.0. I'm registering users via

    Auth0
                .authentication()
                .signUp(
                    email: email,
                    password: password,
                    connection: "Username-Password-Authentication"
                )
                .start { result in
                    DispatchQueue.main.async {
                        self.handleAuthResult(result)
                    }
            }

I tried adding ` parameters: ["grant_type": "implicit"] ` (tried multiple grant_types i have enabled) but no success. 

What to do?

**Comment by hzalaz** [comment]
@haydenholligan you need to enable the grant `Legacy: RO` as detailed in https://auth0.com/docs/clients/client-grant-types#edit-available-grant_types.

However I'd recommend using https://github.com/auth0/Auth0.swift#sign-up-with-database-connection to create the user and then https://github.com/auth0/Auth0.swift#login-with-database-connection-via-realm to login the user (use the one with `realm` instead of `connection` in the parameters). This will shield you from any changes in the future since we are slowing moving away from the legacy grants, Auth0.swift 1.7.0 will have some deprecation in place and will have some documentation stating what grants each method needs (if applicable since not all perform Auth).

**Comment by haydenholligan** [comment]
Cool, I'll try createUser() and realm instead. Shouldn't signUp() be marked as deprecated in Xcode then? This kind of just blindly hit and was very confusing to figure out what was going on.

**Comment by hzalaz** [comment]
It's in master pending our next release, which should be tomorrow

**Comment by hzalaz** [comment]
Well actually it's in a PR but the same things applies

**Comment by haydenholligan** [comment]
Okay. I'm a little confused with the new createUser function. `login()` and the sold `signUp()` both returned `Result<Credentials>`, but `createUser()` just returns a `DatabaseUser` (tuple containing email, username, verified). What's the deal with that? Do I no longer store credentials on a user signup? Or do I call something else to get them? Maybe now I call `login()` following `createUser()`? I'm not entirely sure.

**Comment by hzalaz** [comment]
Yes, the doc on the method should say this too, the `createUser` method just creates the User in a DB connection, then you are responsible of login them or not. The old signup did both at the same time (unless you sent a specific flag).

Now it should be something like to mirror the same behavior

```swift
let email: String = ....
let password: String = ....
Auth0
  .createUser(email: email, password: password, connection: "db_connection")
  .start { result in
    guard case .failure = .success else { return } //notify error
    Auth0
      .login(usernameOrEmail: email, password: password, realm: "db_connection")
      .start { /** Auth result */ }
  }
```

**Comment by haydenholligan** [comment]
I just noticed the docs have `accessToken` everywhere, my code has `idToken`. I'm quite sure I followed the same quickstart guide a few months ago. Was `idToken` replaced with `accessToken`?

**Comment by lbalmaceda** [comment]
@haydenholligan yes, that was replaced a few months ago. Read [this article](https://auth0.com/docs/api-auth/why-use-access-tokens-to-secure-apis) for more context.

**Comment by haydenholligan** [comment]
I see. I figured this issue out, I'm having a new one where `profile.email` is `nil` after creating a user (the email is visible on auth0 dashboard). Should I create a new issue for that?

**Comment by lbalmaceda** [comment]
AFAIK the default requested `scope` is `openid`, which will give you an `access_token` that you can use to [call the /userinfo endpoint](https://github.com/auth0/Auth0.swift#retrieve-user-information) later. If you want the profile in the response to include the `email` you must also ask for the `email` scope when logging in (when you're obtaining the access_token). --> Ask `openid email` scope.

**Comment by haydenholligan** [comment]
Sorry, that's what I'm doing. I'm using the `accessToken` from `login()` to call `userInfo`.The profile I get from `userInfo()` has a `nil` email. The `name` is there though, set as the email address I entered...

**Comment by hzalaz** [comment]
@haydenholligan what userInfo returns depends on the scopes during login and it will only return OIDC standard claims. To get all info you can get from userInfo you should use `openid profile` and that should see the email when you call https://github.com/auth0/Auth0.swift/blob/master/Auth0/Authentication.swift#L342.

If thats not the case I'd suggest you contact us via https://support.auth0.com since we cannot ask for more sensitive information here (like credentials to test, the token, etc)
