### ISSUE TITLE
Authentication().login goes to a background thread but doesn't bring back to main

### ISSUE THREAD

**Issue by SeanLintern** [auth0/Auth0.swift#177]
As title says

`Auth0.authentication().login`

goes onto a background thread, I cant see that stated in the docs and I would of thought it was the responsibility of the call to bring it back to the main thread?

Sorry if this is not the case, this is also the case the creating a user.

**Comment by cocojoe** [comment]
What is your actual issue? That you want to update Ux? In that case you should call the main thread inside your closure and this is your responsibility.  If you want to see this in action, please take a look at the samples:

https://github.com/auth0-samples/auth0-ios-swift-sample

**Comment by SeanLintern** [comment]
No, I think you misunderstand, I am saying that if a method goes to the background thread it should either state it in its docs or bring you back to the main thread when it is done internally, I don't think the user should have to guess the thread the callback will be on?

**Comment by cocojoe** [comment]
Network requests should be handled async as they should never block the main thread. Have a look at [URLSession](https://developer.apple.com/documentation/foundation/urlsession) which is what our network layer uses. You will see the completion handler (callback) is scheduled on the delegate queue.  So this is standard and expected behaviour, no need for us to document this.

In a callback the developer should only switch to the main thread when it is necessary to do so, typically Ux changes. Otherwise they run the risk of unnecessarily blocking the main thread, which goes against best practice.
