### ISSUE TITLE
Add ability to use Auth0 in app extensions

### ISSUE THREAD

**Issue by caitlin615** [auth0/Auth0.swift#184]
In Apple's Developer Docs, `UIApplication.shared` isn't available to app extensions: https://developer.apple.com/library/content/documentation/General/Conceptual/ExtensibilityPG/ExtensionOverview.html#//apple_ref/doc/uid/TP40014214-CH2-SW6

The Auth0 library accesses this here: https://github.com/auth0/Auth0.swift/blob/4c60b8ab8139c303bc463678d8f18f9744f30a9e/Auth0/ControllerModalPresenter.swift#L28

Can you find a way to make your library usable in app extensions?

**Comment by cocojoe** [comment]
This is not something we support and is not in our plans, I have not looked at it in great detail so do not know what is possible. However, if you wish to fork the repo and try out some ideas, I would be interested to see the results.

**Comment by cocojoe** [comment]
Closing, inactivity.

**Comment by mrrhysbutler** [comment]
Just to chime in here, we too are currently integrating auth0 into a notification extension. We get warning:

`ld: warning: linking against a dylib which is not safe for use in application extensions`

on both Auth0 and SimpleKeychain libs.

Our use case is: notification extension needs to access API in background, almost certainly, we need to refresh access token as part of accessing private API. The funny thing is, we are doing this currently (sharing credentials using shared keychain and SimpleKeychain to share refresh token from main app) and things are working great, but all guidance we have had in the past is that apple rejects apps for using libraries with warnings such as this.

It's a shame because I know other swift dependencies are able to support extensions, (I think we can use `@available` `iOSApplicationExtension` possibly?) but if supporting extensions via the API is not currently in the pipeline, would you suggest token refresh simply by using HTTP directly as described in the auth0 docs like this: https://auth0.com/docs/tokens/refresh-token/current ?

**Comment by cocojoe** [comment]
@mrrhysbutler it's not a focus for us. However, if you get it working please raise a PR be happy to review.

**Comment by caitlin615** [comment]
@mrrhysbutler I'm not sure if this will help, but to workaround this issue, I ended up just using the old Lock.swift API client (`pod 'Lock/Core', '~> 1.29.1'`) within the app extension to renew tokens and storing them in the shared keychain. Not an ideal solution since this version likely isn't supported anymore

**Comment by mrrhysbutler** [comment]
Thanks @caitlin615 for the suggestion, and @cocojoe for the feedback.

**Comment by xparabolax** [comment]
Hi, I understand the issue is closed, but it seems that this approach might work to allow Auth0 to be used as a Pod in app extensions. Anywhere UIApplication.shared is used, we may be able to use this instead:

`let application = UIApplication.value(forKeyPath: #keyPath(UIApplication.shared)) as? UIApplication`

Of course, that means that some items that depend on UIApplication.shared returning something won't work, since it returns `nil` in an app extension. But at least we can use the credential gathering portions of Auth0 if we're already logged in.

**Comment by Widcket** [comment]
@caitlin615 and all, we revisited this and got an implementation in the [feature/extensions-support](https://github.com/auth0/Auth0.swift/tree/feature/extensions-support) branch. It doesn't support WebAuth, so it can only be used as an API Client + Credentials manager. Can you try it out and see if it works for you?

**Comment by Widcket** [comment]
@xparabolax yes, you can use the credentials manager in the extensions while using WebAuth in the app.

**Comment by xparabolax** [comment]
@Widcket I have in my Podfile these lines:

```
target 'MainApp' do
  use_frameworks!

  ...

  pod 'Auth0', :git => 'https://github.com/auth0/Auth0.swift.git', :branch => 'feature/extensions-support'
end

target 'Extension' do
  use_frameworks!

  ...

  pod 'Auth0', :git => 'https://github.com/auth0/Auth0.swift.git', :branch => 'feature/extensions-support'
end
```

When I `pod install` for this Podfile, my authentication class cannot resolve `Auth0.webAuth` even though it is only a member of my MainApp target. It provides the error Module 'Auth0' has no member named 'webAuth'.

**Comment by Widcket** [comment]
@xparabolax I went with a runtime check instead of a flag. Can you give it a try please?

**Comment by xparabolax** [comment]
@Widcket That did it! It works perfectly for me. Thank you so much!

**Comment by Widcket** [comment]
This is now out in the [1.23.0 release](https://github.com/auth0/Auth0.swift/releases/tag/1.23.0).
