### ISSUE TITLE
DispatchGroup instead of Semaphore

### ISSUE THREAD

**Issue by adocyn** [auth0/Auth0.swift#734]
### Checklist

- [X] The issue can be reproduced in the [Auth0.swift sample app](https://github.com/auth0-samples/auth0-ios-swift-sample/tree/master/Sample-01) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/Auth0.swift#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/Auth0.swift/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/Auth0.swift/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/tags/c/sdks/5/swift) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

In `CredentialsManager` class in method `retrieveCredentials(...)`, there's a `DispatchGroup`. I think that this should be a Semaphore. We've encounter a bug where Token expires while the app is in the midst of multiple calls to server, and every single one of those calls is asking for a new Token and receives a different Refresh Token. Only the last one is valid for next refresh. So we have a race here. If we're saving the last one (each call overrides Refresh Token) then the app "works". Otherwise it's a logout as the previous Refresh Tokens are expired when new one is issued.

So the process works by "side-effect" (race for Refresh Token, the last call overrides previously saved Refresh Tokens) until it's not. We've encounter a rare situation were two calls we're in a race, and the first one did finish later, overrided the Refresh Token with an expired one and user was logged out.

As this mostly works by the means of the "side-effect", then fixing this bug could be a breaking change.

### Reproduction

Use multiple parallel calls to API in the moment when the Token is expired and observe a situation where multiple calls are being made for Refresh Token.

This issue is probably connected with our implementation where every call to our API is signed, and we're querying the `CredentialsManager` for a Token in parallel (using `credentials(... callback: ...)` method -> which calls `retrieveCredentials(...) `-> which calls to auth0 service for the Token). So in a moment when the Token expires, `CredentialsManager` calls the auth0 service multiple times because there's no Semaphore for that section, and the DispatchGroup does nothing to stop the calls and wait for a result of the first query.

### Auth0.swift version

Current

### Platform

iOS

### Platform version(s)

-

### Xcode version

-

### Package manager

-

**Comment by Widcket** [comment]
Hi @adocyn,

> every single one of those calls is asking for a new Token and receives a different Refresh Token

Check that you're not creating a new instance of the Credentials Manager for every call. This can easily happen, for example, by using a computed property to 'get' the instance –that's actually creating a new one ever time it's called.

We have a unit test for this specific case: https://github.com/auth0/Auth0.swift/blob/master/Auth0Tests/CredentialsManagerSpec.swift#L727

**Comment by Widcket** [comment]
Hi @adocyn, apologies for the delay.

> Token is expired for both operations (it has to be fetched from auth0)

Both unit tests begin with expired credentials:
- "should yield the stored credentials after the previous renewal operation succeeded": https://github.com/auth0/Auth0.swift/blob/master/Auth0Tests/CredentialsManagerSpec.swift#L729
- "should renew the credentials after the previous renewal operation failed": https://github.com/auth0/Auth0.swift/blob/master/Auth0Tests/CredentialsManagerSpec.swift#L750

> Operations are `async`. Currently there are two `sync` operations which means that first will finish and another one will be committed for execution after that.

Scheduling tasks `async` instead of `sync` does not mean that the entire chain of operations for a single `credentials()` call –including the enqueuing of tasks in other queues and the renewal request– will be waited on, and then execution will be resumed with the next line of code. In the context of the unit tests, using `sync` just a convenience because of the way the test expectations are set up.

`credentials()` is async, and it performs async operations:

<img width="582" alt="Screen Shot 2022-08-31 at 00 11 22" src="https://user-images.githubusercontent.com/5055789/187793543-304f4e72-b8d2-43f3-9802-1fa109d3fb82.png">

These async operations will 'escape' both the `sync` call and the [serial queue inside the Credentials Manager](https://github.com/auth0/Auth0.swift/blob/master/Auth0/CredentialsManager.swift#L21). To achieve a serial order of execution, meaning, having the entire chain of async operations for a single `credentials()` call –including the enqueuing of tasks in other queues and the renewal request– happen strictly one at a time, we use a `DispatchGroup` inside the serial queue. Right after scheduling the task, the `DispatchGroup` blocks the serial queue (with `wait()`), and only frees it once the entire chain of sync operations completes, effectively synchronizing it all:

<img width="1013" alt="Screen Shot 2022-08-31 at 19 12 37" src="https://user-images.githubusercontent.com/5055789/187794879-c524f8ce-fc95-4da7-b173-93ffa9ff3a2c.png">

<img width="602" alt="Screen Shot 2022-08-31 at 00 16 47" src="https://user-images.githubusercontent.com/5055789/187793165-e9c2bd8f-2d36-427d-978b-bcb1e578a884.png">

The serial queue is called with `async` to avoid blocking the calling thread. We want to block the queue, not e.g. the main thread. Given that the queue is serial, we can be sure that no other task will be executing concurrently. So even if two calls to `credentials()` from different threads cause both tasks to be enqueued before the first `wait()` executes, one task will still be executed after the other as soon as the first `wait()` runs. If the first task renews the credentials, the second task will simply return the stored renewed credentials.

I added some prints to quickly illustrate what is going on:

<img width="1022" alt="Screen Shot 2022-08-31 at 17 13 01" src="https://user-images.githubusercontent.com/5055789/187791257-2780d956-e919-4552-8318-0b5daa901b7f.png">

Given that concurrency is a complex topic and it's easy to get something wrong, by all means please let me know if something is incorrect and I'll happily look into it.

**Comment by adocyn** [comment]
OK, I see it now with the DispatchQueue being a serial one. Thanks for this extremely good explanation! 🙂
