### ISSUE TITLE
IOS 8+

### ISSUE THREAD

**Issue by ali-hamad** [auth0/Auth0.swift#74]
Can this target IOS 8+ instead of IOS 9+?
or whats the best solution to do if not ?

thanks

**Comment by hzalaz** [comment]
It won't target iOS 8+ since we rely on `SFSafariViewController` for OAuth2 flow and also we believe the user base with iOS 8 is really small to invest the effort of adding a fallback for Safari (WebView which has it's own issues).

You can try using the ObjC version of lock https://github.com/auth0/Lock.iOS-OSX

**Comment by ali-hamad** [comment]
Cool,

i already implemented the lock login, but i plan to use the link , unlink accounts in the auth0 lib so how can i do !

could i use it as rest api ?

**Comment by ali-hamad** [comment]
@hzalaz

**Comment by ali-hamad** [comment]
@cocojoe may i ask about auth0 ios 8 support :P

could use link, unlink accounts as rest api's ?

to overcome the ios 8 issue
