### ISSUE TITLE
CI build error due to recent Package.swift update

### ISSUE THREAD

**Issue by tatsuki-nakano-simplisafe** [auth0/Auth0.swift#776]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/Auth0.swift#readme), [Examples](https://github.com/auth0/Auth0.swift/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/Auth0.swift/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/Auth0.swift/documentation/auth0) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/Auth0.swift/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Hi, our CI tool started to report these error.
It seems these dependencies and Auth0 have been updated Package.swift to drop iOS12 support.
But Auth0 has not been bumped version so SimpleKeychain and JWTDecode fetches latest codes but Auth0 isn't.

❌ error: The package product 'SimpleKeychain' requires minimum platform version 13.0 for the iOS platform, but this target supports 12.0 (in target 'Auth0' from project 'Auth0')
❌ error: The package product 'JWTDecode' requires minimum platform version 13.0 for the iOS platform, but this target supports 12.0 (in target 'Auth0' from project 'Auth0')

### Describe the ideal solution

bump Auth0 version so that SPM aware of latest changes

**Comment by MKE-RobertHaworth** [comment]
This issue is being caused by SimpleKeychain and JWTDecode introducing a minimum deployment mismatch. Due to Auth0 not targeting a specific version of these dependencies or being safeguarded by major version revision changing in the dependencies listed above.

A temporary work around for this is to target explicitly JWTDecode version 3.0.1 and SimpleKeychain version 1.0.1.

If you are targeting Auth0 in a dependency library, you will need to explicitly target these versions of the sub-dependencies in both your primary target and any dependencies chaining these changes in.


I would recommend Auth0 begin targeting explicit versions of the dependencies to guard against breaking change updates like this.

**Comment by tatsuki-nakano-simplisafe** [comment]
as temporary work around, you can specify Auth0 with commit ID: b8e2bf597c9b1d745de2b575e2931dab62321ab9 on SPM

**Comment by tomhopkins** [comment]
Would the work around be effective in Expo? I'm not sure where it would be implemented.

Thanks in advance.

**Comment by Widcket** [comment]
Hi all, thanks for raising this.

We're aligning all our Swift libraries to support iOS 13+. We expect to release a new version of Auth0.swift today.

As mentioned in our [Support Policy](https://github.com/auth0/Auth0.swift#support-policy), dropping unsupported platform versions is not considered a breaking change.

**Comment by tomhopkins** [comment]
Thanks. And fair enough. Apologies: I spent 3 hours trying to work out what I’d done wrong!

From: Rita Zerrizuela ***@***.***>
Date: Thursday, 15 June 2023 at 11:05
To: auth0/Auth0.swift ***@***.***>
Cc: Tom Hopkins ***@***.***>, Comment ***@***.***>
Subject: Re: [auth0/Auth0.swift] CI build error due to recent Package.swift update (Issue #776)

Hi all, thanks for raising this.

We're aligning all our Swift libraries to support iOS 13+. We expect to release a new version of Auth0.swift today.

As mentioned in our Support Policy<https://github.com/auth0/Auth0.swift#support-policy>, dropping unsupported platform versions is not considered a breaking change.

**Comment by bjarnel** [comment]
Same, you broke your own framework Auth0!

**Comment by Widcket** [comment]
Auth0.swift [v2.4.0](https://github.com/auth0/Auth0.swift/releases/tag/2.4.0) is out now!

My apologies for the delay in releasing Auth0.swift respective to JWTDecode.swift and SimpleKeychain, and the CI failures that ensued.

**Comment by tomhopkins** [comment]
Could someone have a look at my follow up. I still can’t build any expo projects with auth0 in them. They work when I take it out.

Tom Hopkins
0776 22 555 30
________________________________

**Comment by MKE-RobertHaworth** [comment]
> Could someone have a look at my follow up. I still can’t build any expo projects with auth0 in them. They work when I take it out. Tom Hopkins 0776 22 555 30
> […](#)

You need to be targeting latest release (2.4.0) and this issue will be resolved. This is working for me as of this morning.

**Comment by tomhopkins** [comment]
Thanks for the reply. Have you seen it working with expo/eas?

**Comment by Widcket** [comment]
@tomhopkins are you using Auth0.swift through the react-native-auth0 SDK? If so, please update to v2.17.4. It should be fixed.

**Comment by michalek-marcin** [comment]
We have the same problem but this time SimpleKeychain and JWTDecode requires minimum version 14.0. Auth0 version we have is `2.10.0`

❌  error: The package product 'SimpleKeychain' requires minimum platform version 14.0 for the iOS platform, but this target supports 13.0 (in target 'Auth0' from project 'Auth0')
❌  error: The package product 'JWTDecode' requires minimum platform version 14.0 for the iOS platform, but this target supports 13.0 (in target 'Auth0' from project 'Auth0')
