### ISSUE TITLE
Versions prior to 2.4.0 (namely the previous one 2.3.2) are not compatible with iOS 12 anymore

### ISSUE THREAD

**Issue by Liquidsoul** [auth0/Auth0.swift#780]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/Auth0.swift#readme), [Examples](https://github.com/auth0/Auth0.swift/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/Auth0.swift/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/Auth0.swift/documentation/auth0) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/Auth0.swift/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

When using the library with a version supporting iOS 12 (in my case the 2.3.2), the transitive dependencies `JWTDecode` and `SimpleKeyChain` are updated to their latest minor versions that do not support iOS 12.

This breaks the iOS 12 support entirely.

### Describe the ideal solution

Auth0 uses the "upToNextMajor" versions of `JWTDecode` and `SimpleKeychain` in its released versions prior to 2.4.0.

As a consequence, the drop of iOS 12 should have triggered a major version bump of `JWTDecode` and `SimpleKeychanin`.

A new version 3.x of JWTDecode should revert the drop of iOS 12 and the drop should be integrated in a 4.x version.
A new version 1.x of SimpleKeychain should revert the drop of iOS 12 and the drop should be integrated in a 2.x version.

### Alternatives and current workarounds

A workaround consists in adding explicitly the 2 dependencies to the project alongside the Auth0 dependency. However, this requires clients to maintain this dependency graph to match the future Auth0 updates which is not ideal.

### Additional context

Sorry for filling this as a feature, I could not find a way to create a "bug" report.

**Comment by Widcket** [comment]
Hi @Liquidsoul, thanks for raising this.

Auth0.swift, SimpleKeychain and JWTDecode.swift all share the same [Support Policy](https://github.com/auth0/Auth0.swift#support-policy) (see their READMEs).

<img width="838" alt="Screenshot 2023-06-20 at 11 19 31 PM" src="https://github.com/auth0/Auth0.swift/assets/5055789/565d793d-33da-4277-9b0c-b5b50bc5775b">

As per the Support Policy, they've been updated to drop support for iOS 12, and this was done in a minor version –which is not considered a breaking change.

> Sorry for filling this as a feature, I could not find a way to create a "bug" report.

Thanks for raising this, turns out there was a problem with our Bug Report template: https://github.com/auth0/Auth0.swift/pull/781

**Comment by Widcket** [comment]
Closing, as I believe the above answers your question.
