### ISSUE TITLE
Custom minTTL support with renew() API

### ISSUE THREAD

**Issue by saltukalakus** [auth0/Auth0.swift#806]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/Auth0.swift#readme), [Examples](https://github.com/auth0/Auth0.swift/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/Auth0.swift/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/Auth0.swift/documentation/auth0) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/Auth0.swift/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

[renew() API](https://github.com/auth0/Auth0.swift/blob/96701ca94eaac75abfe5457542193d6263ba60f7/Auth0/CredentialsManager.swift#L353) doesn't allow setting a custom minTTL. It is currently fixed at 0. 

### Describe the ideal solution

[credentials() API](https://auth0.github.io/Auth0.swift/documentation/auth0/credentialsmanager/credentials(withscope:minttl:parameters:headers:)-11d2f/#declaration) supports setting custom minTTL. Can we support the same with renew() API?

### Additional context

This is a paid customer request, I'm opening this request on behalf of them.

**Comment by Widcket** [comment]
Hi @saltukalakus, thanks for raising this.

Could you please expand a bit on the use case?
`credentials()` supports minTTL because based on it, it could decide to refresh the credentials or return the stored ones. Whereas `renew()` basically means 'renew right now', so minTTL doesn't make sense. What should it do when the minTTL is less than the validity of the current token? Retrieve the stored one? That's what `credentials()` does.

You call `renew()` when you want to renew the token right now, not conditionally.

**Comment by saltukalakus** [comment]
Thanks, @Widcket; from our DM, I understand the use case for `renew()` is to renew the token even if it didn't expire so having a TTL here doesn't make sense. For scenarios where the token may be retrieved from the storage , the `credentials()` API has to be used and then TTL can be an option to retrieve a little bit early. I will close this issue now.
