### ISSUE TITLE
Reason for deprecating tokenInfo

### ISSUE THREAD

**Issue by caitlin615** [auth0/Auth0.swift#85]
Can you explain the reason for deprecating the `tokenInfo` from https://github.com/auth0/Auth0.swift/pull/70?

**Comment by hzalaz** [comment]
@caitlin615 probably the message is not clear enough (will fix it). 
We are trying to move everyone to use `/userinfo` since if you use our OAuth 2.0 features you need to use that endpoint to get the user information (if you don't use it both endpoints works the same), the only change is that in `/userinfo` needs the `access_token` instead of the `id_token`.
