### ISSUE TITLE
Auth0 Failed to build with carthage (0.20.0)

### ISSUE THREAD

**Issue by wendyabrantes** [auth0/Auth0.swift#91]
it's a swift lint violation on enum and switch

[log_error.txt](https://github.com/auth0/Auth0.swift/files/807027/log_error.txt)
<img width="560" alt="screen shot 2017-02-28 at 14 27 48" src="https://cloud.githubusercontent.com/assets/639463/23409067/2ba389d6-fdc2-11e6-8ca8-3c72f7f2a5cd.png">

**Comment by cocojoe** [comment]
Hi @wendyabrantes 

After trawling though that log, it appears the 'build error' is due to `SwiftLint` issues.  So it appears this is probably the local version of SwiftLint, I'm looking at the changelog of swiftlint and apparently breaking changes were introduced in 0.16 and our version is slightly behind.

I'll take a look at it, you can remove this step in the build phase under Auth0.swift in the Carthage checkout.

**Comment by wendyabrantes** [comment]
Ive created a PR
